### ISSUE TITLE
502 on database upload confirmation

### ISSUE THREAD

**Issue by Majorro** [metkm/osu-mutual-finder#19]
STR:
1. Download 1.4.5 release install and open it
2. Click to "Yes" on "Would you like to upload your friend list to database?" popup

Then getting this screen
![Screenshot 2023-11-14 154551](https://github.com/metkm/osu-mutual-finder/assets/35308665/9cd68ebc-f96d-4ab2-9da0-e9458536c6bf)

**Comment by metkm** [comment]
@Majorro Should be fixed
